version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports:
      - '41773:1972'
      - '42773:52773'
      - '43773:53773'
    volumes:
      - ./:/irisrun/repo
