ROUTINE St.OpenAi.ModelNames [Type=INC]

#Define AdaText "text-ada-001"
#Define BabbageText "text-babbage-001"
#Define CurieText "text-curie-001"
#Define DavinciText "text-davinci-003"
#Define CushmanCode "code-cushman-001"
#Define DavinciCode "code-davinci-002"
#Define AdaTextEmbedding "text-embedding-ada-002"
#Define ChatGPTTurbo "gpt-3.5-turbo"
#Define ChatGPTTurbo0301 "gpt-3.5-turbo-0301"
#Define GPT4 "gpt-4"
#Define GPT432kContext "gpt-4-32k"
#Define TextModerationStable "text-moderation-stable"
#Define TextModerationLatest "text-moderation-latest"

#Define DefaultOwnedBy "openai"